export const things = [
  "Journal",
  "Massage oils",
  "Rings",
  "Playlist",
  "Travel journal",
  "Mugs",
  "Letter",
  "Album",
  "Calendar",
  "Puzzle",
  "Locks of hair",
  "Keepsake box",
  "T-shirts",
  "Playlist",
  "Pet",
  "Books",
  "Hobby supplies",
  "Artwork",
  "Hideaway",
  "Candles",
  "Wine glasses",
  "Recipe book",
  "Blanket",
  "Memory jar",
  "Jewelry",
  "Chocolates",
  "Bicycle",
  "Dreams",
  "Garden",
  "Poems",
  "Board game",
  "Photo album",
  "Coupons",
  "Framed photos",
  "Gratitude journal",
  "Photo pillows",
  "Tent",
  "Figurines",
  "Inside jokes",
  "Jersey",
  "Wine corks",
  "Movie collection",
  "Socks",
  "Affirmations",
  "Sketchbook",
  "Keychains",
];
