export const things = {
  Journal: 5,
  "Massage oils": 4,
  Rings: 5,
  Playlist: 3,
  "Travel journal": 5,
  Mugs: 2,
  Letter: 4,
  Album: 4,
  Calendar: 2,
  Puzzle: 2,
  "Locks of hair": 5,
  "Keepsake box": 4,
  "T-shirts": 3,
  Pet: 5,
  Books: 2,
  "Hobby supplies": 2,
  Artwork: 3,
  Hideaway: 5,
  Candles: 2,
  "Wine glasses": 3,
  "Recipe book": 2,
  Blanket: 3,
  "Memory jar": 5,
  Jewelry: 4,
  Chocolates: 2,
  Bicycle: 2,
  Dreams: 5,
  Garden: 3,
  Poems: 4,
  "Board game": 2,
  "Photo album": 4,
  Coupons: 2,
  "Framed photos": 4,
  "Gratitude journal": 5,
  "Photo pillows": 4,
  Tent: 3,
  Figurines: 2,
  "Inside jokes": 5,
  Jersey: 3,
  "Wine corks": 2,
  "Movie collection": 3,
  Socks: 3,
  Affirmations: 4,
  Sketchbook: 4,
  Keychains: 2,
};
